spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/monitoreo_db
spring.datasource.username=postgres
spring.datasource.password=root0987
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=404a635266556a586e3272357538782f413f4428472b4b6250655368566d5971
jwt.expiration=86400000

